'use strict';

var ASSETS = {
	images: [
		'data/arrow_buttons.png',
		'data/bar_bg.png',
		'data/bar_door_highlight.png',
		'data/beer_bottle.png',
		'data/burger_menu.png',
		'data/buttons.png',
		'data/dialog_bg.png',
		'data/doener.png',
		'data/effect_message_bg.png',
		'data/fridge.png',
		'data/fridge_highlight.png',
		'data/home_books.png',
		'data/home_books_highlight.png',
		'data/map.png',
		'data/map_bg.png',
		'data/map_selection.png',
		'data/office_bg.png',
		'data/office_door_highlight.png',
		'data/phone.png',
		'data/phone_highlight.png',
		'data/progress.png',
		'data/room_bg.png',
		'data/room_chest_highlight.png',
		'data/room_door_highlight.png',
		'data/sausage.png',
		'data/street_bar_door_highlight.png',
		'data/street_bg.png',
		'data/street_home_door_highlight.png',
		'data/street_to_supermarket_highlight.png',
		'data/supermarket_buy_bg.png',
		'data/supermarket_door_highlight.png',
		'data/supermarket_food.png',
		'data/supermarket_inside_bg.png',
		'data/supermarket_outside_bg.png',
		'data/supermarket_to_street_highlight.png',
		'data/walk_anim.png',
		'data/walk_anim_gray.png',
		'data/perks.png'
	],
	textures: {
		'data/arrow_up': { image: 'data/arrow_buttons.png', sourceRect: {x: 0, y: 0, sx: 16, sy: 16} },
		'data/arrow_down': { image: 'data/arrow_buttons.png', sourceRect: {x: 0, y: 16, sx: 16, sy: 16} },
		'data/bar_bg': { image: 'data/bar_bg.png' },
		'data/bar_door_highlight': { image: 'data/bar_door_highlight.png' },
		'data/beer_bottle': { image: 'data/beer_bottle.png' },
		'data/burger_menu': { image: 'data/burger_menu.png' },
		'data/buttons': { image: 'data/buttons.png' },
		'data/dialog_bg': { image: 'data/dialog_bg.png' },
		'data/doener': { image: 'data/doener.png' },
		'data/effect_message_bg': { image: 'data/effect_message_bg.png' },
		'data/fridge': { image: 'data/fridge.png' },
		'data/fridge_highlight': { image: 'data/fridge_highlight.png' },
		'data/home_books': { image: 'data/home_books.png' },
		'data/home_books_highlight': { image: 'data/home_books_highlight.png' },
		'data/map': { image: 'data/map.png' },
		'data/map_bg': { image: 'data/map_bg.png' },
		'data/map_selection': { image: 'data/map_selection.png' },
		'data/office_bg': { image: 'data/office_bg.png' },
		'data/office_door_highlight': { image: 'data/office_door_highlight.png' },
		'data/phone': { image: 'data/phone.png' },
		'data/phone_highlight': { image: 'data/phone_highlight.png' },
		'data/progress': { image: 'data/progress.png' },
		'data/room_bg': { image: 'data/room_bg.png' },
		'data/room_chest_highlight': { image: 'data/room_chest_highlight.png' },
		'data/room_door_highlight': { image: 'data/room_door_highlight.png' },
		'data/sausage': { image: 'data/sausage.png' },
		'data/street_bar_door_highlight': { image: 'data/street_bar_door_highlight.png' },
		'data/street_bg': { image: 'data/street_bg.png' },
		'data/street_home_door_highlight': { image: 'data/street_home_door_highlight.png' },
		'data/street_to_supermarket_highlight': { image: 'data/street_to_supermarket_highlight.png' },
		'data/supermarket_buy_bg': { image: 'data/supermarket_buy_bg.png' },
		'data/supermarket_door_highlight': { image: 'data/supermarket_door_highlight.png' },
		'data/supermarket_food_cheap': { image: 'data/supermarket_food.png', sourceRect: {x: 0, y: 0, sx: 200, sy: 125} },
		'data/supermarket_food_expensive': { image: 'data/supermarket_food.png', sourceRect: {x: 200, y: 0, sx: 200, sy: 125} },
		'data/supermarket_food_healthy': { image: 'data/supermarket_food.png', sourceRect: {x: 0, y: 125, sx: 200, sy: 125} },
		'data/supermarket_inside_bg': { image: 'data/supermarket_inside_bg.png' },
		'data/supermarket_outside_bg': { image: 'data/supermarket_outside_bg.png' },
		'data/supermarket_to_street_highlight': { image: 'data/supermarket_to_street_highlight.png' },
		'data/walk_anim': { image: 'data/walk_anim.png' },
		'data/walk_anim_gray': { image: 'data/walk_anim_gray.png' },
		'data/hungry': { image: 'data/perks.png', sourceRect: {x: 0, y: 0, sx: 64, sy: 64} },
		'data/tired': { image: 'data/perks.png', sourceRect: {x: 64, y: 0, sx: 64, sy: 64}  }
	}
}
